### ISSUE TITLE
EOFError: Ran out of input

### ISSUE THREAD

**Issue by R-SPIRIT** [AI-GrandChallenge/round-1#118]
If I input  nsml run -d tr-2 -e main.py -a "--num_epoch 10" line of code I am always receiving "EOFError: Ran out of input" error. Please, help us to solve this problem

**Comment by R-SPIRIT** [comment]
I am receiving the errors below. 


Traceback (most recent call last):
  File "main.py", line 135, in <module>
    main()
  File "main.py", line 91, in main
    load_weight(model, args.weight_file)
  File "main.py", line 56, in load_weight
    model.load_state_dict(torch.load(weight_file)['model'])
  File "/opt/conda/lib/python3.6/site-packages/torch/serialization.py", line 387, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/opt/conda/lib/python3.6/site-packages/torch/serialization.py", line 564, in _load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input
User session exited
