### ISSUE TITLE
nsml.bind load 와 save 경로를 다르게 읽으려고 시도 하여 안되는 문제

### ISSUE THREAD

**Issue by JeiKeiLim** [AI-GrandChallenge/round-1#27]
# Error Log
```
[INFO] nsml_utils.py:20 > Model saved to /tmp/tmpzurznbn2/model.h5
[INFO] main.py:58 > Set the dataset
[INFO] nsml_utils.py:13 > Load weight from /tmp/tmpf84xtruy/model.h5

Traceback (most recent call last):
  File "main.py", line 88, in <module>
    main()
  File "main.py", line 78, in main
    nsml.load(args.checkpoint, session=args.sess_name)
  File "/app/nsml/client.py", line 487, in load
    load_fn(temp_dir)
  File "/app/nsml_utils.py", line 14, in load
    model.load_weights(filename)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 250, in load_weights
    return super(Model, self).load_weights(filepath, by_name, skip_mismatch)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/network.py", line 1259, in load_weights
    with h5py.File(filepath, 'r') as f:
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = '/tmp/tmpf84xtruy/model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
User session exited

```
# main.py 일부
```python
    model = tf.keras.models.load_model(args.path)
    nu.bind_model(model)
    nsml.save(args.checkpoint)
    # ....
    nsml.load(args.checkpoint, session=args.sess_name)
```

# nsml_utils.py
```python
import os

import nsml
import tensorflow as tf
from configuration.config import logger

from utils import inference


def bind_model(model):
    def load(save_folder, **kwargs):
        filename = os.path.join(save_folder, 'model.h5')
        logger.info("Load weight from {}".format(filename))
        model.load_weights(filename)

    def save(save_folder, **kwargs):
        filename = os.path.join(save_folder, 'model.h5')

        model.save(filename, include_optimizer=False)
        logger.info("Model saved to {}".format(filename))

    def infer(data_path, **kwargs):
        return inference(model, data_path)

    nsml.bind(save=save, load=load, infer=infer)

```

NSML 자체적으로 디렉토리 생성해서 저장하는거 같은데 save_folder가 고정되야 정상아닌가요?
아마 temp file 을 써서 저장하는거 같은데 여기서 temp file이 추적이 안되는 모양입니다.
nsml 코드를 볼수도 없으니 난감하네요

**Comment by nsml-admin** [comment]
위처럼 `nsml run`을 한후에 생성된 세션을 `nsml submit`을 이용하면 될것같은데요,

사용했던명령어랑 에러가 발생한 세션 네임을 알려주시면 확인해보겠습니다.

**Comment by JeiKeiLim** [comment]
> 위처럼 `nsml run`을 한후에 생성된 세션을 `nsml submit`을 이용하면 될것같은데요,
> 
> 사용했던명령어랑 에러가 발생한 세션 네임을 알려주시면 확인해보겠습니다.

아 그렇지 않아도 해결 했습니다.

```shell
#nsml run -d tr-4 -e main.py -a "--model-path ./model.h5 --sess_name t0133"
nsml run -d tr-4 -e main.py -a "--model-path ./model.h5 --sess_name t0133/tr-4/67"
```

Session 이름에 t-4/세션 번호를 입력해줘야 하네요.
다른건 몰라도 세션 번호를 자동으로 불러오는 method 는 없을까요?

**Comment by nsml-admin** [comment]
네 세션번호를 자동으로 불러오는 method는 없습니다.

**Comment by JeiKeiLim** [comment]
> 네 세션번호를 자동으로 불러오는 method는 없습니다.

알겠습니다. close 하겠습니다.
