### ISSUE TITLE
[공지] tr-4 leaderboard 초기화 및 계산식 변경

### ISSUE THREAD

**Issue by bluebrush** [AI-GrandChallenge/round-1#62]
먼저, 불편을 드려서 죄송합니다. 

Track4가 real-world application 환경을 가정하여 서로 다른 소스의 데이터를 함께 처리하고 있습니다. 이과정에서 test distribution을 다르게 했는데 geometric mean 특성상 하나의 아마도 소수클래스를 도저히 맞출 수 없는 상황 추정하고 있습니다. 이를 보안하기 위해서 평가 방법을 수정하고 leaderboard를 초기화 하였습니다. 

변경 내용:
평가 방식 산술 평균의 macro f1 score 로 변경

관련 논의:
https://github.com/AI-GrandChallenge/round-1/issues/40

**Comment by 2KangHo** [comment]
```
Traceback (most recent call last):
  File "/app/src/main.py", line 5, in <module>
    nsml.nsml(obj={}, prog_name='nsml')
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/src/nsml_cli/nsml.py", line 648, in submit
    submit_session(ctx, session, checkpoint, verbose, test, entry, realm)
  File "/app/src/nsml_cli/sessions/eval_service.py", line 223, in submit_session
    submit_dict = dict(eval_metric=float(eval_result), params=dict())
ValueError: could not convert string to float: "/usr/local/lib/python3.5/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.\n  'precision', 'predicted', average, warn_for)\n
```
(뒤에 더 숫자가 더있습니다)

제출시 에러가 발생하는데 확인 부탁드립니다.

**Comment by JeiKeiLim** [comment]
ValueError: could not convert string to float: "/usr/local/lib/python3.5/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.\n  'precision', 'predicted', average, warn_for)

저도 같은 에러가 나네요

**Comment by bluebrush** [comment]
@JeiKeiLim , @2KangHo 님, 문제확인하였습니다. 곧 재반영예정입니다. 불편을 드려서 죄송합니다.

**Comment by 2KangHo** [comment]
@bluebrush 네 감사합니다

**Comment by bluebrush** [comment]
@JeiKeiLim , @2KangHo 님
반영되었습니다.
