### ISSUE TITLE
[활용팁] leaderboard 확인 (public/private)

### ISSUE THREAD

**Issue by bluebrush** [AI-GrandChallenge/round-1#64]
login 상태에서 dataset을 클릭하면 내부의 leaderboard를 확인 가능합니다. 
아래 그림에서 private 영역을 클릭하고 public/private 상호 전환이 가능하며, private의 경우 자신이 submit한 이력을 확인할 수 있습니다. 

![image](https://user-images.githubusercontent.com/12540235/88638219-28026800-d0f6-11ea-920e-442935d1b409.png)

**Comment by JuYong-Shin** [comment]
About/ NSML/ Resources/ DataBorad/를 누루면 좌측 상단에 팀명/DataSets 라는 버튼이 있어 눌렀으나,   
제의 submit기록이 안보이고요,  Ranking을 누르면 4개의 특랙 순위가 모두 나오는데, DataSets라는 버튼이 없어집니다.

그리고 제가, 궁금한 것은 
mode가  train에서 sample 데이타가 1개만 있어서인지 
/opt/conda/lib/python3.6/site-packages/scipy/stats/stats.py:338: RuntimeWarning: divide by zero encountered in log
  log_a = np.log(a) 경고가 떴고, 

mode=test일 때는
Traceback (most recent call last):
  File "main.py", line 174, in <module>
    main()
  File "main.py", line 164, in main
    nsml.load(args.checkpoint, session=args.sess_name)
  File "/app/nsml/client.py", line 487, in load
    load_fn(temp_dir)
  File "/app/nsml_utils.py", line 12, in load
    state = torch.load(filename)
  File "/opt/conda/lib/python3.6/site-packages/torch/serialization.py", line 571, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/opt/conda/lib/python3.6/site-packages/torch/serialization.py", line 229, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/opt/conda/lib/python3.6/site-packages/torch/serialization.py", line 210, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp0q7bxo7k/model'
User session exited

이런 error가 있는데,  submit에는 점수가 나왔으니, error가 없었던 같습니다.

위의 두 에러와 submit은 무관한 것이지요?
그리고 위의 두 에러를 해결할  참고 문서를 알려  주시면 감사하겠습니다.

**Comment by bluebrush** [comment]
@JuYong-Shin 님, 우선 leaderboard 확인법에 문구/그림 일부 수정하였습니다.

**Comment by JuYong-Shin** [comment]
예 감사합니다.  확인했습니다. 

그리고 train mode에서 nsml run ~을 실행시키면 checkpoint와 session이 생기는데, 
train mode에서 나온 위 값을 어떻게 test에서 argument로 주는 것으로 해결이  약간 되었는데, 
다른 error가 다시 발생하네요.  조금 살펴보고 질문여부를 정하겠습니다. 
김시합니다.
